### ISSUE TITLE
Simple repair causing crash on fabric 18.4 with mc 1.21.11 upon login.

### ISSUE THREAD

**Issue by matkay521225-png** [4drian3d/SimpleRepair#34]
After upgrading from mc 1.21.10 to 1.21.11 and upgrading all other mods the only thing that would allow my players to log into the newly upgraded 1.21.11 mc server was to remove the simplerepair mod (which we LOVE!).  I hope these notes help.

From my logs.
me.lucko.fabric.api.permissions.v0.Permissions
NoClassDefFoundError: net/minecraft/class_11456

[02:53:17] [User Authenticator #1/INFO]: UUID of player ############ is *************** [02:53:18] [Server thread/INFO]: xyzuser] logged in with entity id 17 at (63.564854509386905, 112.0, -242.71219762087622) [02:53:18] [Server thread/ERROR]: Encountered an unexpected exception java.lang.NoClassDefFoundError: net/minecraft/class_11456 at knot//me.lucko.fabric.api.permissions.v0.Permissions.lambda$check$0(Permissions.java:85) at knot//net.fabricmc.fabric.api.util.TriState.orElseGet(TriState.java:111)

**Comment by matkay521225-png** [comment]
Here's an AI summary:

I’m running a Fabric server on Minecraft 1.21.11 with Fabric Loader 0.18.4, and I’ve run into a crash when a player attempts to log in. After isolating the issue, it looks like the crash is caused by an embedded version of  inside SimpleRepair (or possibly Collective). The mod is attempting to access a class that no longer exists in 1.21.11.
Here’s the relevant error:
java.lang.NoClassDefFoundError: net/minecraft/class_11456
    at me.lucko.fabric.api.permissions.v0.Permissions.lambda$check$0(Permissions.java:85)

This happens immediately after a player joins — the server starts cleanly otherwise.
Would it be possible to rebuild SimpleRepair (and/or Collective) against the latest Fabric API and Minecraft 1.21.11, with updated dependencies? I’d love to keep using it, but right now it’s blocking logins.
Thanks so much for your work on this mod — it’s been a great addition to our server.

**Comment by 4drian3d** [comment]
I will update the mod to be compatible with Minecraft 1.21.11 sometime this week (maybe tomorrow). Thank you for reporting this
